name: NFIL3_ILC
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.12.3
  - conda-forge::pip=24.2
  - pip:
      - jupyter-lab==7.2.2
      - biopython==1.85
      - pandas==2.2.2
      - numpy==1.21.2
      - matplotlib==3.9.2
